### ISSUE TITLE
Error running MySQL script: Exception calling "Fill" with "1" argument(s): "Index was outside the bounds of the array."

### ISSUE THREAD

**Issue by jawandarajbir** [DariuszPorowski/VSTS-MySQL-Toolkit-Win#2]
Hi Dariusz,

I'm trying to run a MySQL script against a ClearDB hosted MySQL database. This script is running just fine using MySQL workbench on same target DB and using exact same credentials. However, when executed on Visual Studio Online build using "Run MySQL script" task, I'm seeing following error. 

`Error running MySQL script: Exception calling "Fill" with "1" argument(s): "Index was outside the bounds of the array."`
![mysql error](https://cloud.githubusercontent.com/assets/3058693/26758645/d09ffe32-4927-11e7-8cc3-5a876152eaed.png)

Appreciate your help here :)

**Comment by DariuszPorowski** [comment]
Hello @jawandarajbir,

I will try to reproduce this issue and investigate the cause.

**Comment by richardacre** [comment]
Bump. Having a similar issue here, but the reported error was "Fatal Error..." instead of "Index was outside..." .. Anyway the "fix" was to not try to create a stored procedure. I think what it needs is a way of manually adding bits to the connection string so that we can (for example) add "AllowUserVariables=true;"

**Comment by DariuszPorowski** [comment]
done in version 0.0.2
